actor:
  config:
    max_phase: 4
  plugin: phase
algorithm:
  config:
    device: cpu
    frap_tls_id: null
    gamma: 0.95
    lr: 0.0001
    num_phase: 4
    phase_2_passable_lanelink: null
    tau: 0.005
  plugin: frap
collector:
  config:
    batch_size: 64
    capacity: 6000
    per_agent: 'false'
  plugin: replay
components:
  actor:
  - phase
  algorithm:
  - frap
  collector:
  - replay
  environment:
  - sumo
  observer:
  - frap
  reward:
  - composite
environment:
  config:
    decision_interval: 5
    flow_file: D:/桌面/ModuTSC/data/Hangzhou1/flow_0.rou.xml
    gui: true
    max_lanelinks: 27
    min_green: 5
    num_phase: 5
    roadnet_file: D:/桌面/ModuTSC/data/Hangzhou1/roadnet.net.xml
    sim_max_time: 3600
    sumo_cfg: ''
    yellow_duration: 3
  plugin: sumo
evaluation:
  checkpoint_dir: checkpoints/custom_Hangzhou1/
  eval_frequency: 5
  eval_steps: 500
experiment:
  name: custom_1779967991590
  seed: 42
observer:
  config:
    features:
    - num
    max_lanelinks: 4
    num_phase: 4
  plugin: frap
orchestrator:
  config: {}
  plugin: test_single
reward:
  config:
    metrics:
      waiting: -1
    reward_norm: 1
  plugin: composite
tracker:
  config:
    sumo_episode_kpis: true
  plugin: console
training:
  episodes_per_epoch: 1
  num_epochs: 20
  warmup_steps: 500
